### ISSUE TITLE
Updating Figure 2: Grid of charts for estimated IDRC by Donor

### ISSUE THREAD

**Issue by Mattie-P** [ONEcampaign/ukraine_oda_tracker#6]
Aim: adapt the current graphs to include the 2022, 2023 and 2024 estimates produced from the new methodology. 

@jm-rivera, to me, the current layout of the graphs still remains the best way to show the estimated cost of refugees in donor countries following the Ukraine crisis. It provides a clear comparison to previous years alongside giving an estimate of how refugee costs will begin to slowly fall moving into the future. 

Do you agree? If so, I am happy to attempt updating the scripts that produce the 5 output CSVs in a new branch. 

(More thought may be required for the first graph, although personally I feel that visualisation is fit for purpose also.)

**Comment by jm-rivera** [comment]
Yes I think we should do that as a starting point.  Sounds good re:a new branch

**Comment by Mattie-P** [comment]
Next, we need to update the unhcr_data.py file

**Comment by Mattie-P** [comment]
Next, we need to update the unhcr_data.py file to use the hcr_data.csv to create columns for 2023 and 2024 ready for the flourish figure.
